/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itca.requerimientos.controller.sbean.jasper;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author dfhernandez
 */
@ManagedBean(name = "jasperBean")
@SessionScoped
public class JasperBean implements Serializable {
    
    //generated by map
    private static Map<String, String> jasperReportOptions;
    static
    {
        jasperReportOptions = new LinkedHashMap<String, String>();
        jasperReportOptions.put("StockByEquipmentModelReport", "Existencia en inventario por modelo");
        jasperReportOptions.put("DefectiveInventoryReport", "Inventario defectuoso");
        jasperReportOptions.put("EquipmentReturnedOverTimeReport", "Prestamos entregados con sobretiempo");
        jasperReportOptions.put("RequestByAssignedTechnicianReport", "Solicitudes por falla y técnico asignado");
        jasperReportOptions.put("RequestByEquipmentFailureReport", "Solicitudes por modelo y falla");
        jasperReportOptions.put("RequestByEquipmentModelReport", "Solicitudes por modelo");
    }
    public Map<String, String> getJasperReportOptions()
    {
        return jasperReportOptions;
    }

    /**
     * Creates a new instance of JasperBean
     */
    public JasperBean() {
    }
    
}